'use client'

import { Sparkles, ChevronDown } from 'lucide-react'
import type { CitationStyle } from '@/types'

const STYLES: CitationStyle[] = ['APA', 'IEEE', 'MLA']

const EXAMPLES = [
  'Deep learning models have demonstrated state-of-the-art performance on image classification tasks. Neural networks with multiple hidden layers can learn hierarchical feature representations. Transfer learning from pre-trained models significantly reduces the need for labeled training data.',
  'Climate change is accelerating the loss of Arctic sea ice at unprecedented rates. Rising global temperatures are causing widespread disruption to ecosystems worldwide. Carbon dioxide concentrations have reached levels not seen in over 800,000 years.',
  'mRNA vaccines have proven highly effective against COVID-19 variants. The immune response generated by mRNA technology is comparable to natural infection. Lipid nanoparticles enable efficient delivery of mRNA into human cells.',
]

interface RawTextAreaProps {
  value:         string
  onChange:      (v: string) => void
  citationStyle: CitationStyle
  onStyleChange: (s: CitationStyle) => void
  onAnalyze:     () => void
  loading:       boolean
  error:         string | null
}

export default function RawTextArea({
  value, onChange, citationStyle, onStyleChange, onAnalyze, loading, error,
}: RawTextAreaProps) {
  const charCount = value.length
  const wordCount = value.trim() ? value.trim().split(/\s+/).length : 0

  return (
    <div className="flex flex-col h-full">
      {/* Textarea */}
      <div className="flex-1 relative">
        <textarea
          value={value}
          onChange={e => onChange(e.target.value)}
          placeholder={`Paste your academic writing here…\n\nReferra will analyze each sentence, detect factual claims, retrieve relevant research papers from Semantic Scholar, and suggest verified citations with confidence scores.\n\nExample: "${EXAMPLES[0].slice(0, 100)}…"`}
          className="w-full h-full resize-none p-5"
          style={{
            fontFamily: 'var(--ff-ui)',
            fontSize: '0.94rem',
            lineHeight: 1.75,
            color: 'var(--text)',
            background: 'var(--surface)',
            border: 'none',
            outline: 'none',
            boxSizing: 'border-box',
          }}
          onKeyDown={e => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) onAnalyze()
          }}
        />

        {/* Character count overlay */}
        {value && (
          <div
            className="absolute bottom-3 right-4"
            style={{ fontFamily: 'var(--ff-mono)', fontSize: '0.56rem', color: 'var(--text-faint)' }}
          >
            {wordCount} words · {charCount} chars
          </div>
        )}
      </div>

      {/* Error */}
      {error && (
        <div className="mx-4 mb-2 px-3 py-2 rounded-md" style={{ background: 'var(--rose-lt)', border: '1px solid var(--rose-bd)' }}>
          <p style={{ fontFamily: 'var(--ff-mono)', fontSize: '0.62rem', color: 'var(--rose)' }}>{error}</p>
        </div>
      )}

      {/* Bottom toolbar */}
      <div
        className="flex items-center gap-3 px-4 py-3 shrink-0"
        style={{ borderTop: '1px solid var(--border)', background: 'var(--surface)' }}
      >
        {/* Citation style selector */}
        <div className="relative">
          <select
            value={citationStyle}
            onChange={e => onStyleChange(e.target.value as CitationStyle)}
            className="appearance-none pr-6 pl-3 py-1.5 rounded-md cursor-pointer"
            style={{
              fontFamily: 'var(--ff-mono)',
              fontSize: '0.68rem',
              fontWeight: 500,
              color: 'var(--text-mid)',
              background: 'var(--surface-2)',
              border: '1px solid var(--border)',
              outline: 'none',
            }}
          >
            {STYLES.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
          <ChevronDown size={11} className="absolute right-2 top-1/2 -translate-y-1/2 pointer-events-none" style={{ color: 'var(--text-muted)' }} />
        </div>

        {/* Tip */}
        <span style={{ fontFamily: 'var(--ff-mono)', fontSize: '0.58rem', color: 'var(--text-faint)', flex: 1 }}>
          ⌘↵ to analyze
        </span>

        {/* Try example */}
        {!value && (
          <button
            onClick={() => onChange(EXAMPLES[Math.floor(Math.random() * EXAMPLES.length)])}
            className="px-3 py-1.5 rounded-md transition-all"
            style={{ fontFamily: 'var(--ff-mono)', fontSize: '0.62rem', color: 'var(--text-muted)', border: '1px solid var(--border)', background: 'var(--surface-2)' }}
            onMouseEnter={e => { e.currentTarget.style.borderColor='var(--indigo-bd)'; e.currentTarget.style.color='var(--indigo)' }}
            onMouseLeave={e => { e.currentTarget.style.borderColor='var(--border)'; e.currentTarget.style.color='var(--text-muted)' }}
          >
            Try example
          </button>
        )}

        {/* Analyze button */}
        <button
          onClick={onAnalyze}
          disabled={loading || !value.trim() || value.trim().length < 20}
          className="flex items-center gap-2 px-4 py-1.5 rounded-md transition-all"
          style={{
            fontFamily: 'var(--ff-ui)',
            fontSize: '0.75rem',
            fontWeight: 600,
            background: loading || !value.trim() ? 'var(--surface-3)' : 'var(--indigo)',
            color: loading || !value.trim() ? 'var(--text-faint)' : '#fff',
            border: '1.5px solid transparent',
            cursor: loading || !value.trim() ? 'not-allowed' : 'pointer',
            boxShadow: loading || !value.trim() ? 'none' : '0 2px 8px rgba(75,95,216,0.3)',
            transition: 'all 0.18s',
          }}
          onMouseEnter={e => {
            if (!loading && value.trim().length >= 20) e.currentTarget.style.background = 'var(--indigo-dk)'
          }}
          onMouseLeave={e => {
            if (!loading && value.trim().length >= 20) e.currentTarget.style.background = 'var(--indigo)'
          }}
        >
          {loading ? (
            <><div className="spinner-sm" />Analyzing…</>
          ) : (
            <><Sparkles size={13} />Analyze Text</>
          )}
        </button>
      </div>
    </div>
  )
}
